site_name: Pyppium
nav:
  - 'index.md'
  - 'installation.md'
  - 'getting-started.md'
  - 'pyppium-driver.md'
  - 'fetcher.md'
  - 'decorators.md'


repo_url: https://github.com/leomenezessz/pyppium

theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  icon:
    repo: fontawesome/brands/github-alt


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite


